# Generated by Django 2.0.6 on 2019-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod_phone_number',
            field=models.IntegerField(),
        ),
    ]
