# Generated by Django 2.0.6 on 2019-09-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0002_auto_20190911_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_phone_number',
            field=models.IntegerField(),
        ),
    ]
